### ISSUE TITLE
bash: roscore: command not found

### ISSUE THREAD

**Issue by sophie-shin** [jetsonhacks/installROSTX2#2]
Hello. Thanks to your video on youtube. I installed several things step by step.
I completely installation with 
1. 'caffe Deep learning Framework - NVIDIA Jetson'
2. 'Build Kernel and Modules - NVIDIA Jetson TX2' without any error.
All screen same like yours.
During the ros installation, every step was all good. I closed window when you close in youtube video.
However, '`roscore`' command was not working...
It shows `' bash: roscore: command not found'.`

**Comment by sophie-shin** [comment]
I reboot and open new terminal and follow below one by one manually, again.
```
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 0xB01FA116
sudo apt-get update
sudo apt-get install ros-kinetic-ros-base -y
sudo apt-get install python-rosdep -y
sudo c_rehash /etc/ssl/certs
sudo rosdep init
rosdep update
echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc
source ~/.bashrc
sudo apt-get install python-rosinstall -y
```
```
and now it's working. sorry for bothering you.

**Comment by jetsonhacks** [comment]
Hi Sophie-shin,
You probably just need to source the bash file, that's where everything gets setup for the ROS environment. You'll see that in lines like:
$ source devel/setup.bash
When you switch to the catkin-workspace
